Job Recommendation System for Students using Machine Learning

🔹 Step 1: Import Libraries

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

🔹 Step 2: Load Dataset

In [2]:
df = pd.read_csv("jobs.csv")
df.head()

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id
0,United States of America,US,NaN,No,jobs.monster.com,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",NaN,http://jobview.monster.com/it-support-technici...,NaN,IT/Software Development,11d599f229a80023d2f40e7c52cd941e
1,United States of America,US,NaN,No,jobs.monster.com,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",Printing and Publishing,http://jobview.monster.com/business-reporter-e...,NaN,NaN,e4cbb126dabf22159aff90223243ff2a
2,United States of America,US,NaN,No,jobs.monster.com,Report this job About the Job DePuy Synthes Co...,Johnson & Johnson Family of Companies Job Appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,Personal and Household Services,http://jobview.monster.com/senior-training-lea...,NaN,NaN,839106b353877fa3d896ffb9c1fe01c0
3,United States of America,US,NaN,No,jobs.monster.com,Why Join Altec? If you’re considering a career...,Engineer - Quality Job in Dixon,Full Time,"Dixon, CA",Altec Industries,http://jobview.monster.com/engineer-quality-jo...,NaN,Experienced (Non-Manager),58435fcab804439efdcaa7ecca0fd783
4,United States of America,US,NaN,No,jobs.monster.com,Position ID# 76162 # Positions 1 State CT C...,Shift Supervisor - Part-Time Job in Camphill,Full Time Employee,"Camphill, PA",Retail,http://jobview.monster.com/shift-supervisor-pa...,NaN,Project/Program Management,64d0272dc8496abfd9523a8df63c184c

🔹 Step 3: Data Preprocessing

In [11]:
# Preprocessing
df = df[['job_title', 'job_description', 'sector', 'location']]
df = df.dropna()

df['combined'] = df['job_title'] + " " + df['job_description'] + " " + df['sector'] + " " + df['location']

🔹 Step 4: Feature Engineering (TF-IDF)

In [12]:
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['combined'])

🔹 Step 5: Similarity Calculation

In [13]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(tfidf_matrix)

🔹 Step 6: Recommendation Function

In [14]:
def recommend_jobs(user_input):
    user_vec = tfidf.transform([user_input])
    sim_scores = cosine_similarity(user_vec, tfidf_matrix)
    
    top_jobs = sim_scores[0].argsort()[-5:][::-1]
    
    return df.iloc[top_jobs][['job_title', 'location', 'sector']]

🔹 Step 7: Test Model

In [15]:
recommend_jobs("Python Data Analysis Machine Learning")

,job_title,location,sector
1558,Machine Learner Researcher Job in Plymouth Mee...,"Plymouth Meeting, PA 19462",Experienced (Non-Manager)
15197,Python Developer Job in Jersey City,"Jersey City, NJ",IT/Software Development
3533,Python Developer Job in Jersey City,"Jersey City, NJ",IT/Software Development
17533,Sr. Python Developer Job in Dallas,Sr. Python Developer,IT/Software Development
1023,eLearning Instructional Designer Job in Dallas,"Dallas, TX",Customer Support/Client Care